spring:
  kafka:
    consumer:
      topic:
        name: "main-topic"

      bootstrap-servers: localhost:9092

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.da.kafkaconsumerservice.deserializer.EmailMessageDeserializer

      group-id: main-topic-consumer
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100



    properties:
      spring.json.trusted.packages: "*"
      max.poll.interval.ms: 300000

      listener:
        concurrency: 3


server:
  port: 8764