server:
  port: 8762
spring:
  data:
    mongodb:
      uri: mongodb://ad_users:ad_users@localhost:27017/usersdb?authSource=admin
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: { ID }
            client-secret: { SECRET }
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

application:
  security:
    jwt:
      secret-key: 404EasdAS7D6Asgsdjajalksd87a7776AAS7D09AASDJXMzllasdpiweeqwej123
      expiration: 86400000
      refresh-token:
        expiration: 604800000
